In [1]:
liste = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(liste)

array([1, 2, 3])

In [4]:
mat = [[1,2,3], [4,5,6], [7,8,9]]

In [5]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((4,5))*8

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(3,3)

array([[0.73223883, 0.07622478, 0.40012682],
       [0.46490208, 0.73013482, 0.0913016 ],
       [0.13769228, 0.3660577 , 0.25285076]])

In [19]:
np.random.randn(10)

array([-0.2020979 , -1.44791124,  0.97985957,  0.59442438,  0.01889923,
        0.06006044,  0.91244123, -0.12948848, -2.06846138, -0.40905376])

In [20]:
np.random.seed(5)

In [21]:
np.random.randint(1,100,10)

array([79, 62, 17, 74,  9, 63, 28, 31, 81,  8])

In [22]:
x = np.arange(25)

In [23]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
x.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
rand_x = np.random.randint(0,50,10)

In [26]:
rand_x

array([12, 15, 49, 39, 16, 27, 44, 13, 11,  1])

In [27]:
rand_x.max()

49

In [28]:
rand_x.min()

1

In [29]:
rand_x.argmax()

2

In [30]:
rand_x.argmin()

9

In [32]:
rand_x.shape

(10,)

In [33]:
rand_x.dtype

dtype('int32')