In [1]:
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[5]

5

In [5]:
x[2:7]

array([2, 3, 4, 5, 6])

In [6]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
x[:5]

array([0, 1, 2, 3, 4])

In [8]:
x[:5] = 20

In [9]:
x

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [10]:
x = np.arange(10)

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x2 = x[:5]

In [14]:
x2

array([0, 1, 2, 3, 4])

In [15]:
x2[:] = 55

In [16]:
x2

array([55, 55, 55, 55, 55])

In [17]:
x

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9])

In [18]:
x_copy = x.copy()

In [19]:
x

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9])

In [20]:
x_copy

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9])

In [21]:
x_copy[:] = 66

In [22]:
x_copy

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 66])

In [23]:
x

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9])

In [24]:
mat = np.array([[10,20,30], [40,50,60], [70,80,90]])

In [25]:
mat

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [27]:
mat[1][2]

60

In [28]:
mat[1,2]

60

In [30]:
mat[:2,1:]

array([[20, 30],
       [50, 60]])

In [31]:
x = np.arange(10)

In [32]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [34]:
bool_x = x<5

In [35]:
bool_x

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [36]:
x[bool_x]

array([0, 1, 2, 3, 4])

In [37]:
x[x>5]

array([6, 7, 8, 9])

In [38]:
x[x<3]

array([0, 1, 2])